### ISSUE TITLE
ClamAV does an update at each run

### ISSUE THREAD

**Issue by rhessing** [jtyr/ansible-clamav#1]
There is a mistake in the tasks/main.yaml file:
```
- name: Check the age of the ClamAV DB
  shell: >
    if (( $(date "+%s") - $(date -d "$(sigtool -i {{ clamav_clamd_database_directory }}/daily.cvd 2>/dev/null | grep -Po '(?<=^Build time: ).*' || echo '2016-01-01')" "+%s") > {{ clamav_db_age }} * 86400 )); then
      exit 1;
    else
      exit 0;
    fi
  register: clamav_db_age_check_result
  failed_when: false
  changed_when: false
  tags:
    - clamav_db
```

The above part will always return false on CentOS 7.3.1611 as the file is not called daily.cvd but daily.lvd on my systems with clamav version: 0.99.2-1

```
# ll /var/lib/clamav/
total 210008
-rw-r--r-- 1 clamscan clamscan    103987 Feb  8 11:01 bytecode.cvd
-rw-r--r-- 1 clamscan clamscan 105791488 Feb  8 10:31 daily.cld
-rw-r--r-- 1 clamscan clamscan 109143933 Feb  8 11:01 main.cvd
-rw------- 1 clamscan clamscan       208 Feb  7 18:30 mirrors.dat
```

The fix for this would be:
`    if (( $(date "+%s") - $(date -d "$(sigtool -i {{ clamav_clamd_database_directory }}/daily.cld 2>/dev/null | grep -Po '(?<=^Build time: ).*' || echo '2016-01-01')" "+%s") > {{ clamav_db_age }} * 86400 )); then`

Next to this issue there is a simmular issue with this part of the playbook code:
```
- name: Update ClamAV DB
  # First delete all DBs if the daily DB is older than 90 days because the
  # mirror server keeps only last 90 daily files.
  shell: >
    if (( $(date "+%s") - $(date -d "$(sigtool -i {{ clamav_clamd_database_directory }}/daily.cvd 2>/dev/null | grep -Po '(?<=^Build time: ).*' || echo '2016-01-01')" "+%s") > 90 )); then
      rm -f {{ clamav_clamd_database_directory }}/*.cvd;
    fi;
    {{ clamav_db_update_command }}
  when: >
    clamav_db_update_run and
    clamav_db_age_check_result.rc or
    clamav_db_update_force
  tags:
    - clamav_db

```

On my systems the above code will always delete the files if an update is required (speaking in terms when the first part of the code has been patched). The reason is because of:

1. daily.cvd is called daily.cld thus it will parse 2016-01-01.
2. the calculated number is always greater then 90 as the date output is in seconds and the comparison number is in days. 

I fixed this on my systems with:
`    if (( $(date "+%s") - $(date -d "$(sigtool -i {{ clamav_clamd_database_directory }}/daily.cld 2>/dev/null | grep -Po '(?<=^Build time: ).*' || echo '2016-01-01')" "+%s") > 90 * 86400 )); then
`

Could you be so kind to check this on your development environment and if this is also the case please update the git repo? The issue could be more complex then I've stated I've not checked any further. I've already patched mine so there is no pressure at all :-) 

Thank you for the great playbook!

**Comment by jtyr** [comment]
Thanks for your comment. I have tested it on the same CentOS version like you but I can not see any clv files. Please revert your changes and try to apply this patch:

```
diff --git a/tasks/main.yaml b/tasks/main.yaml
index 4e553cf..8b16066 100644
--- a/tasks/main.yaml
+++ b/tasks/main.yaml
@@ -142,7 +142,10 @@
 
 - name: Check the age of the ClamAV DB
   shell: >
-    if (( $(date "+%s") - $(date -d "$(sigtool -i {{ clamav_clamd_database_directory }}/daily.cvd 2>/dev/null | grep -Po '(?<=^Build time: ).*' || echo '2016-01-01')" "+%s") > {{ clamav_db_age }} * 86400 )); then
+    if (( $(date "+%s") - $(date -d "$(
+        sigtool -i {{ clamav_clamd_database_directory }}/daily.cvd 2>/dev/null | grep -Po '(?<=^Build time: ).*' ||
+        sigtool -i {{ clamav_clamd_database_directory }}/daily.cld 2>/dev/null | grep -Po '(?<=^Build time: ).*' ||
+        echo '2016-01-01')" "+%s") > {{ clamav_db_age }} * 86400 )); then
       exit 1;
     else
       exit 0;
@@ -157,8 +160,11 @@
   # First delete all DBs if the daily DB is older than 90 days because the
   # mirror server keeps only last 90 daily files.
   shell: >
-    if (( $(date "+%s") - $(date -d "$(sigtool -i {{ clamav_clamd_database_directory }}/daily.cvd 2>/dev/null | grep -Po '(?<=^Build time: ).*' || echo '2016-01-01')" "+%s") > 90 )); then
-      rm -f {{ clamav_clamd_database_directory }}/*.cvd;
+    if (( $(date "+%s") - $(date -d "$(
+        sigtool -i {{ clamav_clamd_database_directory }}/daily.cvd 2>/dev/null | grep -Po '(?<=^Build time: ).*' ||
+        sigtool -i {{ clamav_clamd_database_directory }}/daily.cld 2>/dev/null | grep -Po '(?<=^Build time: ).*' ||
+        echo '2016-01-01')" "+%s") > 90 )); then
+      rm -f {{ clamav_clamd_database_directory }}/*.c?d;
     fi;
     {{ clamav_db_update_command }}
   when: >
```

Please let me know if that works and I will fix it in the master branch.

**Comment by jtyr** [comment]
@rhessing Did you have the opportunity to test the patch? Please let me know.

**Comment by afeld** [comment]
Patch worked for me on RHEL 7.1. Thanks!

/cc @batemapf

**Comment by jtyr** [comment]
Thanks for testing it, @afeld. The change is now [integrated](https://github.com/jtyr/ansible-clamav/commit/cac1abf28944edf537db558d72af4b26add08623) in the role.
