### ISSUE TITLE
OnAccessIncludePath only permits one value

### ISSUE THREAD

**Issue by Kreeblah** [jtyr/ansible-clamav#5]
The ClamAV documentation suggests using multiple OnAccessIncludePath declarations in order to include multiple paths.  For example:

OnAccessIncludePath /home
OnAccessIncludePath /mnt

Both of those lines would be required in order to watch both directories, however if lines are written for both of them in the custom config section, only the last one is entered into the config.  Is there a better way to do this?

**Comment by jtyr** [comment]
Try to define it as a list:

```yaml
OnAccessIncludePath:
  - /home
  - /mnt
```
