### ISSUE TITLE
How to exclude a setting?

### ISSUE THREAD

**Issue by MACscr** [jtyr/ansible-clamav#6]
In order to use a remote clamd tcp server, LocalSocket has to be excluded. While you have support to override values with clamav_clamd_config__custom, I see no way within your role to remove such a config setting. Suggestions?

**Comment by jtyr** [comment]
You can remove it by setting its value to `null`:

```yaml
vars:
  clamav_clamd_local_socket: null
```

**Comment by MACscr** [comment]
So if its set to null it won't set LocalSocket: null? Last time I tested this, it wasn't the case and it simply set that value. I know with 100% certainty that LocalSocket: null in clamd.conf wont work and will try to use Local even though TCP is set. The LocalSocket setting simply cant be defined at all.

**Comment by jtyr** [comment]
Please try to set the above variable in your Playbook and let me know if that worked for you.

**Comment by MACscr** [comment]
It did and thanks!
